---
title: Mike Jick
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
logoimage:
description: PGA Professional
freetext: 30 years experience, Seasonally located in Garden Valley, Idaho and the
  Greater Los Angeles Area
baseurl: "/"
paginate: 3
version: 0.1.0
colorscheme: scheme-gulfracing
ga: UA-123-456
piwikSiteID: 
piwikURL: 
author:
  url: mikejick.com
  name: Mike Jick
github:
  repo: 
gems:
- jekyll-paginate
exclude:
- README.md
- Gemfile.lock
- Gemfile
- "*.gemspec"
- "*.gem"
