---
title: RLStevenson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A Bootstrap based clone of the Hyde theme by mdo.
freetext: Released under an MIT license - feel free to make pull requests.
baseurl: "/"
paginate: 3
version: 0.1.0
colorscheme: scheme-gulfracing
ga: UA-123-456
piwikSiteID: ''
piwikURL: ''
author:
  url: https://www.exchangerate-api.com
  name: ExchangeRate-API
github:
  repo: https://github.com/ExchangeRate-API/rlstevenson-jekyll-theme
gems:
- jekyll-paginate
exclude:
- README.md
- Gemfile.lock
- Gemfile
- "*.gemspec"
- "*.gem"
